 ### Завдання 1

\begin{equation}
1, 3, 6, 7, 8, 11, 16, 18, 19
\end{equation}

### Завдання 2

\begin{equation}
\begin{cases}
x_1 + 2 x_2 + 3 x_3 + 4 x_4 = 5 \\
2 x_1 + x_2 + 2 x_3 + 3 x_4 = 1 \\
3 x_1 + 2 x_2 + x_3 + 2 x_4 = 1 \\
4 x_1 + 3 x_2 + 2 x_3 + x_4 = -5 \\
\end{cases}
\end{equation}

### Завдання 3

\begin{equation}
2(A-B)(A^2 + B)
\end{equation}
, де: \begin{equation} A = \begin{bmatrix}
5 & 1 & 7 \\
-10 & -2 & 1 \\
0 & 1 & 2 \\
\end{bmatrix} \end{equation}

\begin{equation} B = \begin{bmatrix}
2 & 4 & 1 \\
3 & 1 & 0 \\
7 & 2 & 1 \\
\end{bmatrix} \end{equation}

In [29]:
import numpy as np

def task_1_numpy():
    n = int(input("Введіть число n: "))
    arr = np.zeros((n, n), dtype=int)
    np.fill_diagonal(arr, range(1, n+1))
    print(arr)

def task_1_iterative():
    n = int(input("Введіть число n: "))
    arr = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        arr[i][i] = i + 1
    print(arr)

def task_3_numpy():
    n, m, r, c = map(int, input("Введіть 4 числа через пробіл (n, m, r, c): ").split())
    arr = np.ones((n, m), dtype=int)
    arr[r - 1, :] = 0
    arr[:, c - 1] = 0
    print(arr)

def task_3_iterative():
    n, m, r, c = map(int, input("Введіть 4 числа через пробіл (n, m, r, c): ").split())
    arr = [[1 for _ in range(m)] for _ in range(n)]
    arr[r - 1] = [0] * m
    for i in range(n):
        arr[i][c - 1] = 0
    print(arr)

def task_6_numpy():
    arr = np.array(input("Введіть масив чисел через пробіл: ").split(), dtype=int)
    arr[arr != 0] = -1
    print(arr)

def task_6_iterative():
    arr = list(map(int, input("Введіть масив чисел через пробіл: ").split()))
    for i in range(len(arr)):
        if arr[i] != 0:
            arr[i] = -1
    print(arr)

def task_7_numpy():
    arr = np.array(list(map(int, input("Введіть масив чисел через пробіл: ").split())))
    arr[arr == 0] = -1
    print(arr)

def task_7_iterative():
    arr = list(map(int, input("Введіть масив чисел через пробіл: ").split()))
    for i in range(len(arr)):
        if arr[i] == 0:
            arr[i] = -1
    print(arr)

def task_8_numpy():
    arr = np.array(input().split(), dtype=int)
    zeros = np.count_nonzero(arr == 0)
    non_zeros = np.count_nonzero(arr != 0)
    print(f"Нулів: {zeros}\nНе нулів: {non_zeros}")

def task_8_iterative():
    arr = list(map(int, input().split()))
    zeros = 0
    non_zeros = 0
    for num in arr:
        if num == 0:
            zeros += 1
        else:
            non_zeros += 1
    print(f"Нулів: {zeros}\nНе нулів: {non_zeros}")

def task_11_numpy():
    n = int(input("Enter the size of the array: ")) + 2
    arr = np.zeros((n, n), dtype=int)
    arr[1:-1, 1:-1] = 1
    print(arr)

def task_11_iterative():
    n = int(input("Enter the size of the array: ")) + 2
    arr = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(1, n - 1):
        for j in range(1, n - 1):
            arr[i][j] = 1
    for row in arr:
        print(row)

def task_16_numpy():
    n = int(input())
    arr = np.arange(n+1)
    arr[(arr > n/4) & (arr < 3*n/4)] = 0
    print(arr)

def task_16_iterative():
    n = int(input())
    arr = []
    for i in range(n+1):
        if i > n/4 and i < 3*n/4:
            arr.append(0)
        else:
            arr.append(i)
    print(np.array(arr))

def task_18_numpy():
    n = int(input("Введіть кількість чисел у векторі: "))
    vector = np.random.randint(0, 100, n)
    print("Згенерований вектор:", vector)
    unique_count = len(np.unique(vector))
    print("Кількість унікальних чисел у векторі:", unique_count)

def task_18_iterative():
    n = int(input("Введіть кількість чисел у векторі: "))
    vector = [np.random.randint(0, 100) for _ in range(n)]
    print("Згенерований вектор:", vector)
    unique_count = len(set(vector))
    print("Кількість унікальних чисел у векторі:", unique_count)

def task_19_numpy():
    n = int(input("Введіть n: ")) + 1
    vector = np.linspace(0, 1, n, endpoint=False)[1:]  # Generate the vector
    print(np.around(vector, 3))  # Print the vector values rounded to 3 decimal places

def task_19_iterative():
    n = int(input("Введіть n: ")) + 1
    interval_start = 0
    interval_end = 1
    step = (interval_end - interval_start) / n
    vector = []
    current = interval_start + step
    while current < interval_end:
        vector.append(round(current, 3))
        current += step
    print(vector)

In [34]:
tasks = [
    task_1_numpy, task_1_iterative,
    task_3_numpy, task_3_iterative,
    task_6_numpy, task_6_iterative,
    task_7_numpy, task_7_iterative,
    task_8_numpy, task_8_iterative,
    task_11_numpy, task_11_iterative,
    task_16_numpy, task_16_iterative,
    task_18_numpy, task_18_iterative,
    task_19_numpy, task_19_iterative
]

for task in tasks:
    task()

Введіть число n:  10


[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


Введіть число n:  10


[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 3, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 4, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 5, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 6, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 7, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 8, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 9, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]


Введіть 4 числа через пробіл (n, m, r, c):  6 7 2 3


[[1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1]
 [1 1 0 1 1 1 1]
 [1 1 0 1 1 1 1]
 [1 1 0 1 1 1 1]]


Введіть 4 числа через пробіл (n, m, r, c):  6 7 2 3


[[1, 1, 0, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 1, 1, 1, 1], [1, 1, 0, 1, 1, 1, 1], [1, 1, 0, 1, 1, 1, 1], [1, 1, 0, 1, 1, 1, 1]]


Введіть масив чисел через пробіл:  3 4 0 9 7 0 6 0 4 0 3


[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


Введіть масив чисел через пробіл:  3 4 0 9 7 0 6 0 4 0 3


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]


Введіть масив чисел через пробіл:  3 4 0 6 5 0 3 0 4


[ 3  4 -1  6  5 -1  3 -1  4]


Введіть масив чисел через пробіл:  3 4 0 6 5 0 3 0 4


[3, 4, -1, 6, 5, -1, 3, -1, 4]


 3 4 0 9 8 2 4 0 8 4 0


Нулів: 3
Не нулів: 8


 3 4 0 9 8 2 4 0 8 4 0


Нулів: 3
Не нулів: 8


Enter the size of the array:  4


[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


Enter the size of the array:  4


[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]


 10


[ 0  1  2  0  0  0  0  0  8  9 10]


 10


[ 0  1  2  0  0  0  0  0  8  9 10]


Введіть кількість чисел у векторі:  30


Згенерований вектор: [ 6 67 18 60 92  8 92 85 49 61 31 88 23 25 21 96  1 24  4 23  5 58 84 52
 30 80 10 52 70 44]
Кількість унікальних чисел у векторі: 27


Введіть кількість чисел у векторі:  30


Згенерований вектор: [79, 24, 9, 62, 6, 6, 2, 81, 97, 50, 26, 1, 10, 28, 9, 45, 3, 69, 8, 50, 83, 31, 77, 88, 28, 85, 65, 99, 97, 57]
Кількість унікальних чисел у векторі: 25


Введіть n:  10


[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


Введіть n:  10


[0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]


In [36]:
A = np.array([[1, 2, 3, 4],
              [2, 1, 2, 3],
              [3, 2, 1, 2],
              [4, 3, 2, 1]])

B = np.array([5, 1, 1, -5])

# Calculate the determinant of matrix A
det_A = np.linalg.det(A)

# Initialize lists to store solutions
solutions_cramer = []
solutions_matrix_multiplication = []
solutions_inverse_matrix = []
solutions_linalg_solve = []

# Calculate solutions using Cramer's rule
for i in range(A.shape[1]):
    Ai = A.copy()
    Ai[:, i] = B
    solutions_cramer.append(np.linalg.det(Ai) / det_A)

# Calculate solutions using matrix multiplication
solutions_matrix_multiplication = np.linalg.inv(A) @ B

# Calculate solutions using the inverse matrix
solutions_inverse_matrix = np.linalg.inv(A) @ B

# Calculate solutions using numpy.linalg.solve()
solutions_linalg_solve = np.linalg.solve(A, B)

# Compare solutions
print("Cramer's Rule:", solutions_cramer)
print("Matrix Multiplication:", solutions_matrix_multiplication)
print("Inverse Matrix:", solutions_inverse_matrix)
print("Numpy Solve:", solutions_linalg_solve)

# Check if all solutions are close
print("All close:", np.allclose(solutions_cramer, solutions_matrix_multiplication, rtol=1e-05, atol=1e-08))
print("All close:", np.allclose(solutions_cramer, solutions_inverse_matrix, rtol=1e-05, atol=1e-08))
print("All close:", np.allclose(solutions_cramer, solutions_linalg_solve, rtol=1e-05, atol=1e-08))

Cramer's Rule: [-2.0000000000000004, 2.0000000000000027, -3.0, 3.0]
Matrix Multiplication: [-2.  2. -3.  3.]
Inverse Matrix: [-2.  2. -3.  3.]
Numpy Solve: [-2.  2. -3.  3.]
All close: True
All close: True
All close: True


In [4]:
import time
import numpy as np

A = np.array([[5, 1, 7],
              [-10, -2, 1],
              [0, 1, 2]])

B = np.array([[2, 4, 1],
              [3, 1, 0],
              [7, 2, 1]])

# Using NumPy functions
start_time = time.time()
result_numpy = 2 * np.dot(A - B, np.dot(A**2 + B, np.eye(3)))
numpy_time = time.time() - start_time

# Using iterative constructions
start_time = time.time()
result_iterative = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                result_iterative[i, j] += 2 * (A[i, k] - B[i, k]) * (A[k, l]**2 + B[k, l]) * np.eye(3)[l, j]
iterative_time = time.time() - start_time

# Compare results
print("NumPy Result:")
print(result_numpy)
print("\nIterative Result:")
print(result_iterative)

# Compare the results using numpy.allclose()
print("\nResults are close:", np.allclose(result_numpy, result_iterative))

# Print execution times
print("\nNumPy Time:", numpy_time)
print("Iterative Time:", iterative_time)

NumPy Result:
[[ -372.    36.   354.]
 [-1306.  -154. -1296.]
 [ -570.   -74.  -692.]]

Iterative Result:
[[ -372.    36.   354.]
 [-1306.  -154. -1296.]
 [ -570.   -74.  -692.]]

Results are close: True

NumPy Time: 0.0009999275207519531
Iterative Time: 0.0
